# Gunakan image Node.js LTS sebagai base image
FROM node:19-alpine

# Set working directory di container
WORKDIR /app

# Copy package.json dan package-lock.json
COPY package*.json ./

RUN npm install -g sharp
# Install dependencies
RUN npm i

# Copy seluruh kode aplikasi
COPY . .

# Build aplikasi Next.js
ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp
RUN npm run build
VOLUME /app/.next
# Expose port 3000
EXPOSE 3000

# Jalankan aplikasi Next.js dalam mode production
CMD ["npm", "run", "start"]